# Generated by Django 5.1.4 on 2026-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('ip_hash', models.CharField(max_length=64, verbose_name='хэш IP')),
            ],
            options={
                'verbose_name': 'уникальный посетитель',
                'verbose_name_plural': 'уникальные посетители',
                'indexes': [models.Index(fields=['date'], name='analytics_v_date_0e9705_idx')],
                'unique_together': {('date', 'ip_hash')},
            },
        ),
    ]
