# Generated by Django 5.1.4 on 2026-06-27 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('looks', '0002_look_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='название')),
                ('theme', models.CharField(blank=True, max_length=160, verbose_name='тема')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='battles/')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='старт голосования')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='конец голосования')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'баттл',
                'verbose_name_plural': 'баттлы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='battles.battle')),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_entries', to='looks.look')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'участник баттла',
                'verbose_name_plural': 'участники баттла',
                'ordering': ['created_at'],
                'unique_together': {('battle', 'look')},
            },
        ),
        migrations.CreateModel(
            name='BattleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='battles.battle')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='battles.battleentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'голос',
                'verbose_name_plural': 'голоса',
                'unique_together': {('battle', 'user')},
            },
        ),
    ]
