export const PEOPLE = [
  {
    id: 1,
    display_name: "ZAKOS",
    city: "Алматы",
    experience: "8 лет",
    is_verified: true,
    available_for_work: true,
    is_pro: true,
    followers: 12400,
    looks: 34,
    photo: "https://images.unsplash.com/photo-1601412436009-d964bd02edbc?w=600&q=80",
    specialization: "Косплеер",
  },
  {
    id: 2,
    display_name: "NightOwl",
    city: "Астана",
    experience: "5 лет",
    is_verified: true,
    available_for_work: false,
    is_pro: true,
    followers: 8700,
    looks: 21,
    photo: "https://images.unsplash.com/photo-1542385151-efd9000785b0?w=600&q=80",
    specialization: "Косплеер · Фотограф",
  },
  {
    id: 3,
    display_name: "PixelStar",
    city: "Алматы",
    experience: "3 года",
    is_verified: false,
    available_for_work: true,
    is_pro: false,
    followers: 3200,
    looks: 9,
    photo: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&q=80",
    specialization: "Косплеер",
  },
  {
    id: 4,
    display_name: "SteelMage",
    city: "Бишкек",
    experience: "6 лет",
    is_verified: true,
    available_for_work: false,
    is_pro: true,
    followers: 6100,
    looks: 18,
    photo: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&q=80",
    specialization: "Косплеер · Мастер брони",
  },
  {
    id: 5,
    display_name: "MirrorShade",
    city: "Алматы",
    experience: "4 года",
    is_verified: false,
    available_for_work: true,
    is_pro: false,
    followers: 2100,
    looks: 7,
    photo: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&q=80",
    specialization: "Косплеер",
  },
  {
    id: 6,
    display_name: "VoidWalker",
    city: "Астана",
    experience: "7 лет",
    is_verified: true,
    available_for_work: false,
    is_pro: true,
    followers: 9300,
    looks: 28,
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80",
    specialization: "Косплеер · Стилист",
  },
  {
    id: 7,
    display_name: "ArcLight",
    city: "Алматы",
    experience: "2 года",
    is_verified: false,
    available_for_work: true,
    is_pro: false,
    followers: 890,
    looks: 4,
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&q=80",
    specialization: "Косплеер",
  },
  {
    id: 8,
    display_name: "ChromeFox",
    city: "Ташкент",
    experience: "5 лет",
    is_verified: true,
    available_for_work: false,
    is_pro: false,
    followers: 4500,
    looks: 13,
    photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&q=80",
    specialization: "Косплеер · Визажист",
  },
];

export const WORKSHOPS = [
  {
    id: 1,
    name: "7G PRINT LAB",
    type: "3D-печать",
    city: "Алматы",
    is_pro: true,
    is_boosted: true,
    rating: 4.9,
    orders: 240,
    eta: "3–5 дней",
    cover: "https://images.unsplash.com/photo-1631544114551-e3f12e3e1f99?w=700&q=80",
    description: "Профессиональная 3D-печать деталей брони, оружия, аксессуаров. FDM и смола.",
  },
  {
    id: 2,
    name: "EVA FORGE",
    type: "EVA-броня",
    city: "Астана",
    is_pro: true,
    is_boosted: false,
    rating: 4.8,
    orders: 178,
    eta: "7–14 дней",
    cover: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&q=80",
    description: "Ручная работа из EVA-пены. Любой уровень сложности. Полный кастомный пошив.",
  },
  {
    id: 3,
    name: "WigMaster KZ",
    type: "Парики",
    city: "Алматы",
    is_pro: false,
    is_boosted: false,
    rating: 4.7,
    orders: 95,
    eta: "5–10 дней",
    cover: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=700&q=80",
    description: "Парики под заказ, укладка, окраска. Коллекции для конкретных персонажей.",
  },
  {
    id: 4,
    name: "SewPro Studio",
    type: "Пошив",
    city: "Алматы",
    is_pro: true,
    is_boosted: false,
    rating: 4.6,
    orders: 132,
    eta: "10–21 день",
    cover: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=700&q=80",
    description: "Пошив костюмов любой сложности. Японский аниме, западные комиксы, игровые персонажи.",
  },
  {
    id: 5,
    name: "LensLab COS",
    type: "Линзы",
    city: "Астана",
    is_pro: false,
    is_boosted: false,
    rating: 4.5,
    orders: 67,
    eta: "2–3 дня",
    cover: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700&q=80",
    description: "Цветные линзы для косплея, доставка по КЗ. Более 200 оттенков в наличии.",
  },
  {
    id: 6,
    name: "PhotoCraft",
    type: "Фотосъёмка",
    city: "Алматы",
    is_pro: true,
    is_boosted: true,
    rating: 4.9,
    orders: 310,
    eta: "По договорённости",
    cover: "https://images.unsplash.com/photo-1493514789931-586cb221d7a7?w=700&q=80",
    description: "Профессиональные косплей-фотосеты в студии и на выезде. Ретушь включена.",
  },
];

export const EVENTS = [
  {
    id: 1,
    day: "12",
    month: "АПР",
    title: "Edgerunners сет — Алматы",
    city: "Алматы · Студия Orbit",
    going: 23,
  },
  {
    id: 2,
    day: "19",
    month: "АПР",
    title: "Гиб-фест: Весна 2026",
    city: "Астана · ТРЦ Хан Шатыр",
    going: 148,
  },
  {
    id: 3,
    day: "03",
    month: "МАЙ",
    title: "Косплей-сходка Ташкент",
    city: "Ташкент · Парк Навои",
    going: 62,
  },
  {
    id: 4,
    day: "17",
    month: "МАЙ",
    title: "Anime Convention Almaty",
    city: "Алматы · KЦДК",
    going: 380,
  },
];
