# Generated by Django 5.1.4 on 2026-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80, verbose_name='ник')),
                ('bio', models.TextField(blank=True, verbose_name='о себе')),
                ('roles', models.JSONField(default=list, verbose_name='роли')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='аватар')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='обложка')),
                ('available_for_work', models.BooleanField(default=False, verbose_name='свободен для заказов')),
                ('experience', models.CharField(blank=True, max_length=60, verbose_name='опыт')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('accent_color', models.CharField(default='#ff2d6f', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('handle', models.CharField(max_length=120)),
                ('is_connected', models.BooleanField(default=False)),
            ],
        ),
    ]
