# Generated by Django 5.1.4 on 2026-06-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_from_catalog',
            field=models.BooleanField(default=False, verbose_name='скрыт из каталога'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinned_look_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='закреплённые образы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True, verbose_name='ссылка /u/'),
        ),
    ]
