# Generated by Django 5.1.4 on 2026-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_hide_from_catalog_profile_pinned_look_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='donation_methods',
            field=models.JSONField(blank=True, default=list, verbose_name='приём донатов'),
        ),
    ]
