# Generated by Django 5.1.4 on 2026-07-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_donation_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='роль')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='role_media/logos/', verbose_name='логотип роли')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='role_media/covers/', verbose_name='обложка роли')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_media', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'медиа роли',
                'verbose_name_plural': 'медиа ролей',
                'unique_together': {('profile', 'role')},
            },
        ),
    ]
