# Generated by Django 5.1.4 on 2026-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_rolemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mascot',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='маскот-компаньон (Pro)'),
        ),
    ]
