# Generated by Django 5.1.4 on 2026-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_mascot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='название')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='код')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mascots/', verbose_name='картинка')),
                ('image_url', models.CharField(blank=True, max_length=300, verbose_name='картинка по ссылке')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'маскот',
                'verbose_name_plural': 'маскоты',
                'ordering': ['order', 'id'],
            },
        ),
    ]
