# Generated by Django 5.1.4 on 2026-06-04 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('type', models.CharField(choices=[('print3d', '3D-печать'), ('eva', 'EVA'), ('sewing', 'Швейная'), ('wigs', 'Парики')], max_length=20, verbose_name='тип')),
                ('city', models.CharField(max_length=80, verbose_name='город')),
                ('about', models.TextField(blank=True, verbose_name='описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='workshops/')),
                ('eta', models.CharField(blank=True, max_length=40, verbose_name='срок')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('is_pro', models.BooleanField(default=False, verbose_name='PRO-тариф')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price_from', models.PositiveIntegerField(verbose_name='цена от, ₸')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workshops.workshop')),
            ],
        ),
    ]
