# Generated by Django 5.1.4 on 2026-06-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_remove_workshop_is_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshops/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workshops.workshop')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
