# Generated by Django 5.1.4 on 2026-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_workshopphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/logos/', verbose_name='логотип'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='workshops/', verbose_name='обложка'),
        ),
    ]
