# Generated by Django 5.1.4 on 2026-07-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshop_logo_alter_workshop_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='instagram',
            field=models.CharField(blank=True, max_length=120, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='телефон / WhatsApp'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='site',
            field=models.CharField(blank=True, max_length=200, verbose_name='сайт'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='telegram',
            field=models.CharField(blank=True, max_length=80, verbose_name='Telegram'),
        ),
    ]
