# Generated by Django 5.1.4 on 2026-07-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_workshop_instagram_workshop_phone_workshop_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='type',
            field=models.CharField(choices=[('print3d', '3D-печать'), ('eva', 'EVA-пена'), ('sewing', 'Швейная'), ('wigs', 'Парики')], max_length=20, verbose_name='тип'),
        ),
    ]
