# Generated by Django 5.1.4 on 2026-06-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_guide_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guides/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='guides.guide')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
