# Generated by Django 5.1.4 on 2026-07-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='название')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CuratedPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('look', 'Образ (розовый, крупный)'), ('workshop', 'Мастерская (голубой)'), ('event', 'Событие (жёлтый)')], default='look', max_length=20, verbose_name='стиль карточки')),
                ('tag', models.CharField(blank=True, help_text='Напр. ★ Образ недели', max_length=60, verbose_name='метка')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('meta', models.CharField(blank=True, help_text='Напр. 12 400 просмотров · 890 ♥', max_length=200, verbose_name='подпись')),
                ('link', models.CharField(blank=True, help_text='Напр. /people/1 или https://…', max_length=300, verbose_name='ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='curated/', verbose_name='картинка (файл)')),
                ('image_url', models.URLField(blank=True, help_text='Альтернатива загрузке файла', max_length=500, verbose_name='картинка (ссылка)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'выбор редакции',
                'verbose_name_plural': 'выбор редакции',
                'ordering': ['order', 'id'],
            },
        ),
    ]
