# Generated by Django 5.1.4 on 2026-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedpick',
            name='style',
            field=models.CharField(choices=[('look', 'Образ (розовый)'), ('workshop', 'Мастерская (голубой)'), ('event', 'Событие (жёлтый)'), ('battle', 'Баттл (фиолетовый)'), ('team', 'Команда (зелёный)'), ('shoot', 'Съёмка (оранжевый)'), ('guide', 'Гайд (жёлтый)'), ('rent', 'Прокат (голубой)'), ('shop', 'Магазин/товар (розовый)')], default='look', max_length=20, verbose_name='стиль карточки'),
        ),
    ]
