# Generated by Django 5.1.4 on 2026-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='что нужно')),
                ('budget', models.PositiveIntegerField(blank=True, null=True, verbose_name='бюджет, ₸')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='дедлайн')),
                ('status', models.CharField(choices=[('request', 'Заявка'), ('accepted', 'Принят'), ('in_work', 'В работе'), ('shipped', 'Отправлен'), ('done', 'Получен'), ('cancelled', 'Отменён')], default='request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
