# Generated by Django 5.1.4 on 2026-07-02 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_unify_pro_tariff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('pro', 'Оплата Pro'), ('donate_site', 'Донат сайту')], max_length=20, verbose_name='назначение')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='валюта')),
                ('months', models.PositiveSmallIntegerField(default=1, verbose_name='месяцев Pro')),
                ('order_id', models.CharField(max_length=64, unique=True, verbose_name='наш ид заказа')),
                ('invoice_uuid', models.CharField(blank=True, max_length=64, verbose_name='uuid Cryptomus')),
                ('pay_url', models.URLField(blank=True, max_length=500, verbose_name='ссылка на оплату')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка/отмена')], default='pending', max_length=20, verbose_name='статус')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='оплачено')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='сырой ответ/вебхук')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Плательщик (может быть пусто для анонимного доната)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
