# Generated by Django 5.1.4 on 2026-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('nowpayments', 'NOWPayments'), ('cryptomus', 'Cryptomus')], default='cryptomus', max_length=20, verbose_name='шлюз'),
        ),
    ]
