# Generated by Django 5.1.4 on 2026-07-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('nowpayments', 'NOWPayments'), ('cryptomus', 'Cryptomus')], default='nowpayments', max_length=20, verbose_name='шлюз'),
        ),
    ]
