# Generated by Django 5.1.4 on 2026-07-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_payment_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('cryptopay', 'Crypto Pay'), ('nowpayments', 'NOWPayments'), ('cryptomus', 'Cryptomus')], default='cryptopay', max_length=20, verbose_name='шлюз'),
        ),
    ]
