# Generated by Django 5.1.4 on 2026-06-27 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='название')),
                ('character', models.CharField(blank=True, max_length=160, verbose_name='персонаж / фандом')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('size', models.CharField(blank=True, max_length=40, verbose_name='размер')),
                ('price_day', models.PositiveIntegerField(blank=True, null=True, verbose_name='цена/сутки ₸')),
                ('deposit', models.PositiveIntegerField(blank=True, null=True, verbose_name='залог ₸')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='город')),
                ('image', models.ImageField(blank=True, null=True, upload_to='costumes/')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('rented', 'В аренде'), ('unavailable', 'Недоступен')], default='available', max_length=12, verbose_name='статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'костюм',
                'verbose_name_plural': 'костюмы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='с')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='по')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='комментарий')),
                ('status', models.CharField(choices=[('pending', 'Заявка'), ('approved', 'Подтверждена'), ('declined', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=12, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('costume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rentals.costume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заявка на аренду',
                'verbose_name_plural': 'заявки на аренду',
                'ordering': ['-created_at'],
            },
        ),
    ]
