# Generated by Django 5.1.4 on 2026-06-27 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0003_workshopphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='город')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('looking_for', models.JSONField(blank=True, default=list, verbose_name='ищем роли')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='shoots/')),
                ('status', models.CharField(choices=[('open', 'Набор открыт'), ('full', 'Команда собрана'), ('done', 'Прошла'), ('cancelled', 'Отменена')], default='open', max_length=12, verbose_name='статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoots_as_location', to=settings.AUTH_USER_MODEL, verbose_name='локация (профиль)')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoots', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoots', to='workshops.workshop', verbose_name='мастерская (костюм/реквизит)')),
            ],
            options={
                'verbose_name': 'съёмка',
                'verbose_name_plural': 'съёмки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShootParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cosplayer', 'Косплеер'), ('photographer', 'Фотограф'), ('model', 'Модель'), ('location', 'Локация'), ('workshop', 'Мастерская'), ('other', 'Другое')], default='cosplayer', max_length=20, verbose_name='роль')),
                ('status', models.CharField(choices=[('invited', 'Приглашён'), ('requested', 'Заявка'), ('confirmed', 'В команде'), ('declined', 'Отклонён')], default='requested', max_length=12, verbose_name='статус')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='shoots.shoot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoot_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'участник съёмки',
                'verbose_name_plural': 'участники съёмки',
                'ordering': ['created_at'],
                'unique_together': {('shoot', 'user')},
            },
        ),
    ]
