# Generated by Django 5.1.4 on 2026-07-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('url', models.URLField(max_length=500, verbose_name='ссылка')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='логотип')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='логотип по ссылке')),
                ('tier', models.CharField(choices=[('general', 'Генеральный'), ('partner', 'Партнёр')], default='partner', max_length=20, verbose_name='уровень')),
                ('card_text', models.CharField(blank=True, max_length=160, verbose_name='текст карточки')),
                ('show_strip', models.BooleanField(default=True, verbose_name='в лого-полосе')),
                ('show_feed', models.BooleanField(default=False, verbose_name='карточкой в ленте')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'партнёр',
                'verbose_name_plural': 'партнёры',
                'ordering': ['order', 'id'],
            },
        ),
    ]
