# Generated by Django 5.1.4 on 2026-06-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looks', '0002_look_team'),
        ('workshops', '0003_workshopphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='stage',
            field=models.CharField(choices=[('planned', 'Хочу скосплеить'), ('wip', 'В работе'), ('done', 'Готов')], default='done', max_length=10, verbose_name='стадия'),
        ),
        migrations.CreateModel(
            name='LookUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='что сделано')),
                ('image', models.ImageField(blank=True, null=True, upload_to='looks/wip/', verbose_name='фото этапа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='looks.look')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='look_updates', to='workshops.workshop', verbose_name='мастерская (заказал тут)')),
            ],
            options={
                'verbose_name': 'этап работы',
                'verbose_name_plural': 'этапы работы',
                'ordering': ['created_at'],
            },
        ),
    ]
