# Generated by Django 5.1.4 on 2026-06-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looks', '0003_look_stage_lookupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='boosted_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='продвижение в ленте до'),
        ),
    ]
